import type { Metadata } from "next";
import LegalPage from "@/components/common/LegalPage";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "Terms of service for the Vaidya Gogate Memorial Foundation website.",
};

export default function TermsPage() {
  return (
    <LegalPage
      eyebrow="Legal"
      title="Terms of Service"
      description="By using the Vaidya Gogate Memorial Foundation website and services you agree to these terms."
      lastUpdated="Sept 2026"
      sections={[
        {
          title: "About the Foundation",
          body: "The Vaidya Gogate Memorial Foundation is a charitable organisation dedicated to Ayurveda, education, research and community service. This website provides information about the Foundation, its events, publications, clinics and services.",
        },
        {
          title: "Accounts",
          body: "To register for events, purchase books or access certificates you must create an account. You agree to provide accurate information and to keep your login credentials secure. Your 12-digit Account ID is generated by our systems and must not be treated as a password.",
        },
        {
          title: "Event Registrations",
          body: "Registration for an event is confirmed once payment is completed (where fees apply) or your application is approved. Tickets are non-transferable unless stated otherwise. Participation certificates are issued in accordance with each event's configuration.",
        },
        {
          title: "Orders & Shipping",
          body: "Book orders are processed once payment is received. Delivery timelines are estimates. Please refer to our Shipping and Refund policies for details.",
        },
        {
          title: "Certificate Verification",
          body: "Certificate verification confirms that a certificate number matches the Foundation's records. Verification does not constitute any other endorsement by the Foundation.",
        },
        {
          title: "Acceptable Use",
          body: "You agree not to misuse the website, attempt unauthorised access, or use information from the website for purposes inconsistent with the Foundation's charitable mission.",
        },
        {
          title: "Limitation of Liability",
          body: "The Foundation does not provide medical advice through this website. Information about Ayurveda is provided for general awareness. For specific health concerns, please consult a qualified physician.",
        },
      ]}
    />
  );
}