import Link from "next/link";

interface AccountCreatedProps {
  accountId: string;
  name: string;
}

export default function AccountCreated({
  accountId,
  name,
}: AccountCreatedProps) {
  return (
    <div className="text-center">
      <div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-emerald-50 text-2xl text-emerald-600">
        ✓
      </div>

      <p className="mt-6 text-sm font-semibold uppercase tracking-[0.18em] text-burgundy">
        Account Created
      </p>

      <h2 className="mt-2 text-3xl font-bold text-text-primary">
        Welcome, {name}
      </h2>

      <p className="mx-auto mt-3 max-w-md text-sm leading-6 text-text-muted">
        Your Vaidya Gogate Memorial Foundation account has been
        successfully created.
      </p>

      <div className="mx-auto mt-8 max-w-md rounded-2xl border border-burgundy/15 bg-burgundy/5 p-7">
        <p className="text-xs font-semibold uppercase tracking-[0.18em] text-text-muted">
          Your Account ID
        </p>

        <p className="mt-3 text-3xl font-bold tracking-[0.12em] text-burgundy">
          {accountId}
        </p>

        <p className="mt-3 text-xs text-text-muted">
          This 12-digit Account ID is generated by our backend after your
          email and WhatsApp are verified. Keep it for future
          registrations and support.
        </p>
      </div>

      <div className="mt-7 flex flex-wrap items-center justify-center gap-3">
        <Link href="/account" className="btn-primary">
          Go to My Account
        </Link>
        <Link href="/" className="btn-outline">
          Continue to Website
        </Link>
      </div>
    </div>
  );
}